# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hotel_pb2 as hotel__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hotel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserverChambre = channel.unary_unary(
                '/hotel.ReservationService/ReserverChambre',
                request_serializer=hotel__pb2.ReservationRequest.SerializeToString,
                response_deserializer=hotel__pb2.ReservationResponse.FromString,
                _registered_method=True)
        self.VerifierDisponibilite = channel.unary_unary(
                '/hotel.ReservationService/VerifierDisponibilite',
                request_serializer=hotel__pb2.DisponibiliteRequest.SerializeToString,
                response_deserializer=hotel__pb2.DisponibiliteResponse.FromString,
                _registered_method=True)
        self.AnnulerReservation = channel.unary_unary(
                '/hotel.ReservationService/AnnulerReservation',
                request_serializer=hotel__pb2.AnnulationRequest.SerializeToString,
                response_deserializer=hotel__pb2.AnnulationResponse.FromString,
                _registered_method=True)
        self.ConsulterReservations = channel.unary_unary(
                '/hotel.ReservationService/ConsulterReservations',
                request_serializer=hotel__pb2.ConsultationRequest.SerializeToString,
                response_deserializer=hotel__pb2.ConsultationResponse.FromString,
                _registered_method=True)
        self.AjouterChambre = channel.unary_unary(
                '/hotel.ReservationService/AjouterChambre',
                request_serializer=hotel__pb2.ChambreRequest.SerializeToString,
                response_deserializer=hotel__pb2.ChambreResponse.FromString,
                _registered_method=True)
        self.SupprimerChambre = channel.unary_unary(
                '/hotel.ReservationService/SupprimerChambre',
                request_serializer=hotel__pb2.ChambreRequest.SerializeToString,
                response_deserializer=hotel__pb2.ChambreResponse.FromString,
                _registered_method=True)
        self.GetAllChambres = channel.unary_stream(
                '/hotel.ReservationService/GetAllChambres',
                request_serializer=hotel__pb2.Empty.SerializeToString,
                response_deserializer=hotel__pb2.Chambre.FromString,
                _registered_method=True)


class ReservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReserverChambre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifierDisponibilite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnulerReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsulterReservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AjouterChambre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SupprimerChambre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllChambres(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserverChambre': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserverChambre,
                    request_deserializer=hotel__pb2.ReservationRequest.FromString,
                    response_serializer=hotel__pb2.ReservationResponse.SerializeToString,
            ),
            'VerifierDisponibilite': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifierDisponibilite,
                    request_deserializer=hotel__pb2.DisponibiliteRequest.FromString,
                    response_serializer=hotel__pb2.DisponibiliteResponse.SerializeToString,
            ),
            'AnnulerReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnulerReservation,
                    request_deserializer=hotel__pb2.AnnulationRequest.FromString,
                    response_serializer=hotel__pb2.AnnulationResponse.SerializeToString,
            ),
            'ConsulterReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsulterReservations,
                    request_deserializer=hotel__pb2.ConsultationRequest.FromString,
                    response_serializer=hotel__pb2.ConsultationResponse.SerializeToString,
            ),
            'AjouterChambre': grpc.unary_unary_rpc_method_handler(
                    servicer.AjouterChambre,
                    request_deserializer=hotel__pb2.ChambreRequest.FromString,
                    response_serializer=hotel__pb2.ChambreResponse.SerializeToString,
            ),
            'SupprimerChambre': grpc.unary_unary_rpc_method_handler(
                    servicer.SupprimerChambre,
                    request_deserializer=hotel__pb2.ChambreRequest.FromString,
                    response_serializer=hotel__pb2.ChambreResponse.SerializeToString,
            ),
            'GetAllChambres': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllChambres,
                    request_deserializer=hotel__pb2.Empty.FromString,
                    response_serializer=hotel__pb2.Chambre.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotel.ReservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReserverChambre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.ReservationService/ReserverChambre',
            hotel__pb2.ReservationRequest.SerializeToString,
            hotel__pb2.ReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifierDisponibilite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.ReservationService/VerifierDisponibilite',
            hotel__pb2.DisponibiliteRequest.SerializeToString,
            hotel__pb2.DisponibiliteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnulerReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.ReservationService/AnnulerReservation',
            hotel__pb2.AnnulationRequest.SerializeToString,
            hotel__pb2.AnnulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsulterReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.ReservationService/ConsulterReservations',
            hotel__pb2.ConsultationRequest.SerializeToString,
            hotel__pb2.ConsultationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AjouterChambre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.ReservationService/AjouterChambre',
            hotel__pb2.ChambreRequest.SerializeToString,
            hotel__pb2.ChambreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SupprimerChambre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.ReservationService/SupprimerChambre',
            hotel__pb2.ChambreRequest.SerializeToString,
            hotel__pb2.ChambreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllChambres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hotel.ReservationService/GetAllChambres',
            hotel__pb2.Empty.SerializeToString,
            hotel__pb2.Chambre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
